# Generated by Django 4.0.5 on 2022-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35)),
                ('domaine', models.CharField(max_length=40)),
                ('type_ent', models.CharField(choices=[('Privee', 'Pivee'), ('Mixte', 'Mixte'), ('Publique', 'Publique')], max_length=80, null=True)),
                ('email', models.EmailField(max_length=80)),
                ('adresse', models.CharField(max_length=500)),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
