# Generated by Django 4.0.5 on 2022-07-23 21:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projets',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
