# Generated by Django 4.0.5 on 2022-07-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('prestataire', models.CharField(max_length=50)),
                ('modalites_paiement', models.CharField(choices=[('mensuel', 'MENSUEL'), ('trimestriel', 'TRIMESTRIEL'), ('annuel', 'ANNUEL'), ('autre', 'AUTRE')], max_length=30, null=True)),
                ('montant_percu', models.CharField(choices=[('frc', 'FRC'), ('usd', 'USD'), ('autre', 'AUTRE')], max_length=40, null=True)),
                ('caissier', models.CharField(max_length=20)),
                ('percepteur', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('observation', models.TextField()),
            ],
        ),
    ]
