# Generated by Django 4.0.5 on 2022-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GestionProjets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entreprise_contractante', models.CharField(max_length=50)),
                ('etat_travaux', models.CharField(choices=[('en instance', 'En instance'), ('moins avances', 'Moins avances'), ('avances', 'Avances'), ('tres avances', 'Tres avances'), ('finis', 'Finis')], max_length=100, null=True)),
                ('date_debut', models.CharField(max_length=20)),
                ('date_fin', models.CharField(max_length=20)),
                ('paiement', models.CharField(choices=[('prefinancement', 'Prefinancement'), ('acompte', 'Acompte'), ('cash', 'Cash')], max_length=100, null=True)),
                ('observation', models.TextField()),
            ],
        ),
    ]
